(deftheme origamid-next
  "Created 2020-11-16.")

(custom-theme-set-faces
 'origamid-next
 '(default ((t (:inherit nil :extend nil :stipple nil :background "#222222" :foreground "#FFFFFF" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal))))
 '(cursor ((t (:background "#FFFFFF"))))
 '(fixed-pitch ((t (:family "Source Code Pro" :foundry "ADBO" :width normal :height 145 :weight normal :slant normal))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((t (:foreground "#88CC44"))))
 '(homoglyph ((t (:foreground "#88CC44"))))
 '(minibuffer-prompt ((t (:foreground "#888888"))))
 '(highlight ((t (:background "#444466" :foreground "#FFFFFF"))))
 '(region ((t (:extend t :background "#444466" :foreground "#FFFFFF"))))
 '(shadow ((t (:foreground "#333333"))))
 '(secondary-selection ((t (:extend t :background "#4E415C"))))
 '(trailing-whitespace ((t (:background "#964C7B"))))
 '(font-lock-builtin-face ((t (:foreground "#EB64B9"))))
 '(font-lock-comment-delimiter-face ((t (:inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:foreground "#91889B"))))
 '(font-lock-constant-face ((t (:foreground "#B381C5"))))
 '(font-lock-doc-face ((t (:foreground "#919ea7" :inherit (font-lock-comment-face)))))
 '(font-lock-function-name-face ((t (:foreground "#EB64B9"))))
 '(font-lock-keyword-face ((t (:foreground "#40B4C4"))))
 '(font-lock-negation-char-face ((t (:foreground "#40B4C4" :inherit (bold)))))
 '(font-lock-preprocessor-face ((t (:foreground "#40B4C4" :inherit (bold)))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#40B4C4" :inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#40B4C4" :inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "#B4DCE7"))))
 '(font-lock-type-face ((t (:foreground "#FFE261"))))
 '(font-lock-variable-name-face ((t (:foreground "#FFFFFF"))))
 '(font-lock-warning-face ((t (:inherit (warning)))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:weight bold :underline (:color foreground-color :style line) :foreground "#40B4C4"))))
 '(link-visited ((t (:foreground "violet" :inherit (link)))))
 '(fringe ((t (:foreground "#4E415C" :inherit (default)))))
 '(header-line ((t (:foreground "#FFFFFF" :background "#27212E"))))
 '(tooltip ((t (:foreground "#FFFFFF" :background "#1B1720"))))
 '(mode-line ((t (:box nil :foreground "#1B1720" :background "#ED60BA"))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:foreground "#1B1720"))))
 '(mode-line-highlight ((t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:box nil :foreground "#544863" :background "#231d29"))))
 '(isearch ((t (:weight bold :inherit (lazy-highlight)))))
 '(isearch-fail ((t (:weight bold :foreground "#222228" :background "#964C7B"))))
 '(lazy-highlight ((t (:weight bold :foreground "#ECEFF4" :background "#336A79"))))
 '(match ((t (:weight bold :foreground "#74DFC4" :background "#222228"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'origamid-next)
